# Generated by Django 4.1.4 on 2022-12-10 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
